### ISSUE TITLE
error in link

### ISSUE THREAD

**Issue by niallroche** [accordproject/cicero-perishable-network#3]
the following link is returning a 404 https://github.com/accordproject/cicero-template-library/tree/master/perishable-goods
it is mentioned in the text 'The Cicero contract is at: '

**Comment by jeromesimeon** [comment]
The correct link is https://github.com/accordproject/cicero-template-library/tree/master/src/perishable-goods

I'm suspecting this sample is quite outdated, though. Not sure if we want to deprecate it or maintain it.
